export const MOVIES_LOADING='MOVIES_LOADING';
export const MOVIES_FAILED='MOVIES_FAILED';
export const ADD_MOVIES='ADD_MOVIES'

export const USER_REVIEWS_LOADING='USER_REVIEWS_LOADING';
export const USER_REVIEWS_FAILED='USER_REVIEWS_FAILED';
export const ADD_USER_REVIEWS='ADD_USER_REVIEWS';
export const NEW_USER_REVIEW='NEW_USER_REVIEW';

export const RECOMMENDATIONS_LOADING='RECOMMENDATIONS_LOADING';
export const RECOMMENDATIONS_FAILED='RECOMMENDATIONS_FAILED';
export const ADD_RECOMMENDATIONS='ADD_RECOMMENDATIONS';

export const AUTH_STATE_LOADING='AUTH_STATE_LAODING';
export const AUTH_STATE_FAILED='AUTH_STATE_FAILED';
export const ADD_AUTH_STATE='ADD_AUTH_STATE';
export const AUTH_STATE_LOGOUT='AUTH_STATE_LOGOUT';
export const UPDATE_AUTH_STATE='UPDATE_AUTH_STATE';